apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scriptforge.fullname" . }}-config
data:
  SCRIPTFORGE_LISTEN_ADDR: ":8080"
  SCRIPTFORGE_MODE: "controller"
  SCRIPTFORGE_EXEC_NAMESPACE: {{ .Values.execution.podNamespace | quote }}
  SCRIPTFORGE_WORKER_SLOTS: "10"
  SCRIPTFORGE_LOG_RETENTION: "72h"
  SCRIPTFORGE_RUNTIME_IMAGES: "bash={{ .Values.runtimeImages.bash }},python={{ .Values.runtimeImages.python }},terraform={{ .Values.runtimeImages.terraform }},powershell={{ .Values.runtimeImages.powershell }},ansible={{ .Values.runtimeImages.ansible }}"
  {{- if .Values.publicBaseURL }}
  SCRIPTFORGE_PUBLIC_BASE_URL: {{ .Values.publicBaseURL | quote }}
  {{- end }}
  {{- with .Values.githubOAuth }}
  {{- if .clientId }}
  SCRIPTFORGE_GITHUB_OAUTH_CLIENT_ID: {{ .clientId | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.oidc }}
  {{- if .issuer }}
  SCRIPTFORGE_OIDC_ISSUER: {{ .issuer | quote }}
  {{- end }}
  {{- if .clientId }}
  SCRIPTFORGE_OIDC_CLIENT_ID: {{ .clientId | quote }}
  {{- end }}
  {{- end }}
